bs : 64 # batch size
lr : 1e-4 # learning rate
wd : 1e-6 # weight decay 
epochs : 30

image_encoder : "resnet18"
image_embedding : 2048
text_encoder : "distilbert-base-uncased"
text_embedding : 768
text_tokenizer : "distilbert-base-uncased"
max_length : 200

pretrained : True # for both image encoder and text encoder
trainable : all-layers # ["last-layer", "all-layers"]
temperature : 1.0

# image size
size : 224

# for projection head; used for both image and text encoders
num_projection_layers : 1
projection_dim : 256
dropout : 0
