bs : 64 # batch size
lr : 1e-4 # learning rate
wd : 1e-6 # weight decay 
epochs : 30

image_encoder : "vit_base_patch16_224" 
image_embedding : 2048

pretrained : True # for both image encoder and text encoder
trainable : all-layers # ["last-layer", "all-layers"]
temperature : 1.0

# image size
size : 224

# for projection head; used for both image and text encoders
num_projection_layers : 1
projection_dim : 256
dropout : 0
